### ISSUE TITLE
请教一下参考的书是哪一本？3d大师？

### ISSUE THREAD

**Issue by zhouhang95** [yangzhenzhuozz/Renderer#1]

**Comment by yangzhenzhuozz** [comment]
我也是一个初学者，正在尝试添加新内容到这个项目里面，自己也可以顺便学习，参考书籍比较多《计算机图形学 opengl版》、本科时候的图形学课本和维基百科上面的一些知识

**Comment by zhouhang95** [comment]
https://github.com/ssloy/tinyrenderer/wiki

我最近发现了个这个 感兴趣可以看一下 作为补充

**Comment by yangzhenzhuozz** [comment]
这是个好项目，我学习一下
